# Generated by Django 6.1.1 on 2026-10-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='vehicle_photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/vehicle/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
