# Generated by Django 6.1.1 on 2026-09-25 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create_order', models.DateTimeField(auto_now_add=True)),
                ('address_load', models.CharField(max_length=200)),
                ('address_delivery', models.CharField(max_length=200)),
                ('date_delivery', models.DateTimeField(blank=True, null=True)),
                ('cargo_description', models.TextField()),
                ('cargo_weight_tons', models.FloatField(blank=True, null=True)),
                ('cargo_volume_m3', models.FloatField(blank=True, null=True)),
                ('contact_name', models.CharField(max_length=60)),
                ('contact_phone', models.CharField(max_length=12)),
                ('porters', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('searching', 'Ищем водителя'), ('in_progress', 'На выполнении'), ('done', 'Заказ выполнен'), ('cancelled', 'Заказ отменён')], default='pending', max_length=20)),
                ('required_drivers', models.PositiveIntegerField(default=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CargoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='cargo/%Y/%m/%d/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_photo', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driver_orders', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_drivers', to='orders.order')),
            ],
        ),
    ]
