# Generated by Django 6.1.1 on 2026-09-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cargo_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
