# Generated by Django 6.1.1 on 2026-10-02 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_cargo_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_delivery',
            new_name='date_loading',
        ),
    ]
