# Generated by Django 6.1.1 on 2026-10-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_date_delivery_order_date_loading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargofoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cargo/%Y/%m/%d/'),
        ),
    ]
